### ISSUE TITLE
Week 2 Activity 3

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [jordynbx/stardewValleyAssistant#1]
Hi @jordynbx ! Looks like you have a good start setting up your project structure! Can you also be sure to finish up activity 3 by adding in your problem statement, time log, etc.?

![Screen Shot 2021-02-01 at 12 50 48 PM](https://user-images.githubusercontent.com/13874466/106508726-5a6c9380-6492-11eb-9ace-41992abcd67d.png)

**Comment by jordynbx** [comment]
Thank you, I somehow totally missed this. It is all set.

**Comment by pawaitemadisoncollege** [comment]
Looks good now! Thanks!
