### ISSUE TITLE
Checkpoint #3 is ready for review 

### ISSUE THREAD

**Issue by jordynbx** [jordynbx/stardewValleyAssistant#7]
@pawaitemadisoncollege checkpoint #3 is ready for review

AWS link: http://18.219.146.156:8080/StardewValleyAssistant/index.jsp

Signing up for an account should work, but just in case it doesn't, you can use jordyn/admin to log in. Here are a few examples of crops in the you can search for: strawberry, potato, corn, wheat

**Comment by pawaitemadisoncollege** [comment]
Good morning! Would you be able to bounce your ec2 instance in the aws console? I'm not able to access the application and I'm assuming it just needs a quick restart. It looks like you have a LOT of functionality underway and I'm looking forward to seeing this in action!

- [ ] Regarding the todo here: https://github.com/jordynbx/stardewValleyAssistant/blob/0def9b48b43b7a899de8f7db5ce2a1789686dd4b/src/main/java/edu.matc/controller/LogoutAction.java#L37-L43.  You may already have thought of this, but you could set a request attribute that displays on the index.jsp.

**Comment by pawaitemadisoncollege** [comment]
Yes! good catch! You could need to forward in order to pass the attribute in the request.  The other option would be to put the log out confirmation message in the session, which will be available after the redirect.

**Comment by pawaitemadisoncollege** [comment]
I'm still not able to get in :( - Is port 8080 open to all ips?  

![Screen Shot 2021-03-24 at 9 50 27 AM](https://user-images.githubusercontent.com/13874466/112331273-c5626b80-8c86-11eb-9bdc-40bfdc93f427.png)

**Comment by jordynbx** [comment]
@pawaitemadisoncollege 
Oh shoot. I just added the a new rule and bounced it, should this allow access from anywhere?![image](https://user-images.githubusercontent.com/60451192/112332133-7d901400-8c87-11eb-822e-ae1d71600dfd.jpeg)

**Comment by jordynbx** [comment]
@pawaitemadisoncollege At this point I have no idea what to do. For me it works on my computer, on my phone turned off wifi, on a VPN, and on GeoPeeker, but for my husband on his work computer through a VPN it doesn't work. Since it works for me no matter what I try I'm finding it difficult to test and troubleshoot.

**Comment by pawaitemadisoncollege** [comment]
Sorry for the frustration!  Can you try only specifying one inbound source for port 8080, by removing your 71.82... ip? I wonder if that one is conflicting with the "anywhere" setting.

**Comment by jordynbx** [comment]
@pawaitemadisoncollege Done - let me know if that works

**Comment by pawaitemadisoncollege** [comment]
YES! LOVE the styling you've done! 

![Screen Shot 2021-03-24 at 11 56 33 AM](https://user-images.githubusercontent.com/13874466/112351697-1c247100-8c98-11eb-8702-d0b7e386c718.png)
![Screen Shot 2021-03-24 at 11 56 45 AM](https://user-images.githubusercontent.com/13874466/112351706-1d559e00-8c98-11eb-9043-d87eddbed328.png)

**Comment by pawaitemadisoncollege** [comment]
Just following up after poking around a bit more - you have a LOT implemented already! Congratulations! 

One thing in the flow that I noticed  - what do you think about navigating the user right to the Login screen after they complete Sign up?

**Comment by jordynbx** [comment]
Yes, I'm so glad it worked!! The extra spring break time really helped. :) 

And yes, navigating right to the log in page makes more sense then what I'm doing now - if they signed up they surely want to log in right after. I will update that!
